### ISSUE TITLE
Add support 1.20.1

### ISSUE THREAD

**Issue by ShrikerChestTree** [GravityCY/ViewBobbingOptions#1]
I noticed that your mod does not support version 1.20.1 please add this in the next version

**Comment by GravityCY** [comment]
Sir, yes sir! Currently trying to figure out how to do that, starting from 1.19 to 1.20.1, will be done soon probably

**Comment by GravityCY** [comment]
I have released the mod from 1.19 upto 1.20.1 (in theory).
