### ISSUE TITLE
Incompatibility with Figura mod

### ISSUE THREAD

**Issue by m0oncatcher** [GravityCY/ViewBobbingOptions#2]
error: https://mclo.gs/rjiVSjm

**Comment by GravityCY** [comment]
This error doesn't say that my mod is causing the crash, it's saying that the mod `Make Bubbles Pop` has a mixin that is failing to apply. That's what's causing the error. Try removing it. As far as I can see `Make Bubbles Pop` only supports 1.20.4 at the moment, and you're trying to use it with 1.21

**Comment by GravityCY** [comment]
Yeah you're right, I thought mixin failures crashed the game

I don't see how my mod is crashing the game cause it's crashing where I'm initializing my keybind, I see that after that figura does some stuff. So, I wanna say this is not an issue of my mod, and more an issue of figura, cause nothing in this error is telling me, this is an issue of my mod

**Comment by m0oncatcher** [comment]
I did submit an issue there too, if i have any new info i will update here.

**Comment by GravityCY** [comment]
Alright I've gotten some advice, and turns out I can fix it. I'll try and update it for 1.20-1.21, but not guaranteed, since I'd like to update the mod with the newest Minecraft versions.

**Comment by GravityCY** [comment]
I've released a fix from 1.20 up to 1.21, try it and let me know it's good so we can close this.

**Comment by m0oncatcher** [comment]
Seems to be working as expected. Its incredible how fast you fixed it, thank you for your work.
